using RavenDbTest.Console.Entities;

namespace RavenVsMongo.Entities
{
    public class Person
    {
        public string Id { get; set; }
        public string CategoryId { get; set; }
        public GenderType Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public string Text9 { get; set; }
        public string Text10 { get; set; }
        public string MutchLongerTextPropertyName1 { get; set; }
        public string MutchLongerTextPropertyName2 { get; set; }
        public string MutchLongerTextPropertyName3 { get; set; }
        public string MutchLongerTextPropertyName4 { get; set; }
        public string MutchLongerTextPropertyName5 { get; set; }
        public string MutchLongerTextPropertyName6 { get; set; }
        public string MutchLongerTextPropertyName7 { get; set; }
        public string MutchLongerTextPropertyName8 { get; set; }
        public string MutchLongerTextPropertyName9 { get; set; }
        public string MutchLongerTextPropertyName10 { get; set; }
        public string MutchLongerTextPropertyName11 { get; set; }
        public string MutchLongerTextPropertyName12 { get; set; }
        public string MutchLongerTextPropertyName13 { get; set; }
        public string MutchLongerTextPropertyName14 { get; set; }
        public string MutchLongerTextPropertyName15 { get; set; }
        public string MutchLongerTextPropertyName16 { get; set; }
        public string MutchLongerTextPropertyName17 { get; set; }
        public string MutchLongerTextPropertyName18 { get; set; }
        public string MutchLongerTextPropertyName19 { get; set; }
        public string MutchLongerTextPropertyName20 { get; set; }
        public string MutchLongerTextPropertyName21 { get; set; }
        public string MutchLongerTextPropertyName22 { get; set; }
        public string MutchLongerTextPropertyName23 { get; set; }
        public string MutchLongerTextPropertyName24 { get; set; }
        public string MutchLongerTextPropertyName25 { get; set; }
        public string MutchLongerTextPropertyName26 { get; set; }
        public string MutchLongerTextPropertyName27 { get; set; }
        public string MutchLongerTextPropertyName28 { get; set; }
        public string MutchLongerTextPropertyName29 { get; set; }
        public string MutchLongerTextPropertyName30 { get; set; }
        public string MutchLongerTextPropertyName31 { get; set; }
        public string MutchLongerTextPropertyName32 { get; set; }
        public string MutchLongerTextPropertyName33 { get; set; }
        public string MutchLongerTextPropertyName34 { get; set; }
        public string MutchLongerTextPropertyName35 { get; set; }
        public string MutchLongerTextPropertyName36 { get; set; }
        public string MutchLongerTextPropertyName37 { get; set; }
        public string MutchLongerTextPropertyName38 { get; set; }
        public string MutchLongerTextPropertyName39 { get; set; }
        public string MutchLongerTextPropertyName40 { get; set; }
        public string MutchLongerTextPropertyName41 { get; set; }
        public string MutchLongerTextPropertyName42 { get; set; }
        public string MutchLongerTextPropertyName43 { get; set; }
        public string MutchLongerTextPropertyName44 { get; set; }
        public string MutchLongerTextPropertyName45 { get; set; }
        public string MutchLongerTextPropertyName46 { get; set; }
        public string MutchLongerTextPropertyName47 { get; set; }
        public string MutchLongerTextPropertyName48 { get; set; }
        public string MutchLongerTextPropertyName49 { get; set; }
        public string MutchLongerTextPropertyName50 { get; set; }
        public string MutchLongerTextPropertyName51 { get; set; }
        public string MutchLongerTextPropertyName52 { get; set; }
        public string MutchLongerTextPropertyName53 { get; set; }
        public string MutchLongerTextPropertyName54 { get; set; }
        public string MutchLongerTextPropertyName55 { get; set; }
        public string MutchLongerTextPropertyName56 { get; set; }
        public string MutchLongerTextPropertyName57 { get; set; }
        public string MutchLongerTextPropertyName58 { get; set; }
        public string MutchLongerTextPropertyName59 { get; set; }
        public string MutchLongerTextPropertyName60 { get; set; }
        public string MutchLongerTextPropertyName61 { get; set; }
        public string MutchLongerTextPropertyName62 { get; set; }
        public string MutchLongerTextPropertyName63 { get; set; }
        public string MutchLongerTextPropertyName64 { get; set; }
        public string MutchLongerTextPropertyName65 { get; set; }
        public string MutchLongerTextPropertyName66 { get; set; }
        public string MutchLongerTextPropertyName67 { get; set; }
        public string MutchLongerTextPropertyName68 { get; set; }
        public string MutchLongerTextPropertyName69 { get; set; }
        public string MutchLongerTextPropertyName70 { get; set; }
        public string MutchLongerTextPropertyName71 { get; set; }
        public string MutchLongerTextPropertyName72 { get; set; }
        public string MutchLongerTextPropertyName73 { get; set; }
        public string MutchLongerTextPropertyName74 { get; set; }
        public string MutchLongerTextPropertyName75 { get; set; }
        public string MutchLongerTextPropertyName76 { get; set; }
        public string MutchLongerTextPropertyName77 { get; set; }
        public string MutchLongerTextPropertyName78 { get; set; }
        public string MutchLongerTextPropertyName79 { get; set; }
        public string MutchLongerTextPropertyName80 { get; set; }
        public string MutchLongerTextPropertyName81 { get; set; }
        public string MutchLongerTextPropertyName82 { get; set; }
        public string MutchLongerTextPropertyName83 { get; set; }
        public string MutchLongerTextPropertyName84 { get; set; }
        public string MutchLongerTextPropertyName85 { get; set; }
        public string MutchLongerTextPropertyName86 { get; set; }
        public string MutchLongerTextPropertyName87 { get; set; }
        public string MutchLongerTextPropertyName88 { get; set; }
        public string MutchLongerTextPropertyName89 { get; set; }
        public string MutchLongerTextPropertyName90 { get; set; }
        public string MutchLongerTextPropertyName91 { get; set; }
        public string MutchLongerTextPropertyName92 { get; set; }
        public string MutchLongerTextPropertyName93 { get; set; }
        public string MutchLongerTextPropertyName94 { get; set; }
        public string MutchLongerTextPropertyName95 { get; set; }
        public string MutchLongerTextPropertyName96 { get; set; }
        public string MutchLongerTextPropertyName97 { get; set; }
        public string MutchLongerTextPropertyName98 { get; set; }
        public string MutchLongerTextPropertyName99 { get; set; }



    }
}